package usecases

const (
	authUN = "AuthUseCase"
)

const (
	errBeginTx                  = "failed to begin transaction"
	errCheckEmail               = "failed to check email"
	errCheckUsername            = "failed to check username"
	errCreateActivityAttempt    = "failed to create activity attempt"
	errCreateActivityLog        = "failed to create activity log"
	errCreateOtp                = "failed to create otp"
	errCreateUser               = "failed to create user"
	errCreateUserSession        = "failed to create user session"
	errCreateToken              = "failed to create token"
	errDecryptText              = "failed to decrypt text"
	errEncryptText              = "failed to encrypt text"
	errExceedMaxLoginAttempts   = "failed to get exceed max login attempts"
	errFindOtp                  = "failed to find otp"
	errFindUserByEmail          = "failed to find user by email"
	errFindUserSession          = "failed to find user session"
	errFindTokenData            = "failed to find token data"
	errGenerateJWT              = "failed to generate jwt"
	errHashPassword             = "failed to hash password"
	errHashText                 = "failed to hash text"
	errIsUserCanRequestOtp      = "failed to check if user can request otp"
	errSendEmail                = "failed to send email"
	errRefreshUserSession       = "failed to refresh user session"
	errResolveLastLoginAttempts = "failed to resolve last login attempts"
	errRevokeTokens             = "failed to revoke tokens"
	errUpdateOtpUsed            = "failed to update otp used at"
	errUpdateTokenData          = "failed to update token data"
	errUpdateUser               = "failed to update user"
	invalidEmailPassword        = "invalid email or password"
	invalidOTP                  = "invalid otp"
	invalidPassword             = "invalid password"
	invalidVerificationData     = "invalid verification data"
	invalidResetPasswordData    = "invalid reset password data"
	loginSuccess                = "login success"
	maxLoginAttemptsExceeded    = "max login attempts exceeded"
	maxRequestOtpExceeded       = "max request otp exceeded"
	userBlocked                 = "user is blocked"
)
